### ISSUE TITLE
 Getting this error: Expected name to be an item, was unknown string 'forbidden_arcanus:abysshroom

### ISSUE THREAD

**Issue by Jordan231111** [stal111/Forbidden-Arcanus#154]
21.03 20:09:48 [Server] Worker-Main-11/ERROR Couldn't parse loot table forbidden_arcanus:blocks/abysshroom
21.03 20:09:48 [Server] INFO com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'forbidden_arcanus:abysshroom'

**Comment by ModernGamingWorld** [comment]
Yep Same issue

[29Mar2021 11:44:13.184] [Render thread/ERROR] [net.minecraft.loot.LootTableManager/]: Couldn't parse loot table forbidden_arcanus:blocks/abysshroom
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'forbidden_arcanus:abysshroom'
	at net.minecraft.util.JSONUtils.func_219793_a(SourceFile:127) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:401) ~[?:?]
	at net.minecraft.util.JSONUtils.func_188172_b(SourceFile:127) ~[?:?]
	at net.minecraft.util.JSONUtils.func_188180_i(SourceFile:135) ~[?:?]
	at net.minecraft.loot.ItemLootEntry$Serializer.func_212829_b_(SourceFile:55) ~[?:?]
	at net.minecraft.loot.ItemLootEntry$Serializer.func_212829_b_(SourceFile:40) ~[?:?]
	at net.minecraft.loot.StandaloneLootEntry$Serializer.func_230421_b_(SourceFile:151) ~[?:?]
	at net.minecraft.loot.StandaloneLootEntry$Serializer.func_230421_b_(SourceFile:129) ~[?:?]
	at net.minecraft.loot.LootEntry$Serializer.func_230423_a_(SourceFile:86) ~[?:?]
	at net.minecraft.loot.LootEntry$Serializer.func_230423_a_(SourceFile:74) ~[?:?]
	at net.minecraft.loot.LootTypesManager$Serializer.deserialize(SourceFile:83) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?]
	at net.minecraft.util.JSONUtils.func_188174_a(SourceFile:448) ~[?:?]
	at net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:183) ~[?:?]
	at net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:180) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?]
	at net.minecraft.util.JSONUtils.func_188177_a(SourceFile:456) ~[?:?]
	at net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:252) ~[?:?]
	at net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:249) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[gson-2.8.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:880) ~[forge:?]
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1425) ~[?:?]
	at dev.latvian.kubejs.core.LootTablesKJS.applyKJS0(LootTablesKJS.java:24) ~[kubejs:1605.3.6-build.178]
	at net.minecraft.loot.LootTableManager.redirect$zio000$applyKJS(LootTableManager.java:1021) ~[?:?]
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38) ~[?:?]
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16) ~[?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863) ~[?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1715) ~[?:?]
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1681) ~[?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:254) ~[?:?]
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:309) ~[?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:99) ~[fpsreducer:mc1.16.4-1.18]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.2.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]

**Comment by stal111** [comment]
Should no longer happen in the newest beta.
