### ISSUE TITLE
com.google.gson.JsonParseException: Error loading registry data: Unknown tag: forbidden_arcanus:darkstone_ore_replaceables 1.18 crash

### ISSUE THREAD

**Issue by ModernGamingWorld** [stal111/Forbidden-Arcanus#222]
[crash-2022-01-04_17.11.55-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7810963/crash-2022-01-04_17.11.55-client.txt)

**Comment by willtarax** [comment]
I am also getting this error. I am not working with a published modpack, I am working on my own personal modpack.

**Comment by Klouver-github** [comment]
happens to me as well

**Comment by iron-shennon** [comment]
[crash-2022-01-07_14.09.59-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7830565/crash-2022-01-07_14.09.59-client.txt)

Just happened to me as well. I added F&A to ATM7 with valhelsia_core-1.18.1-0.3.0.

**Comment by jkwphysics** [comment]
[crash-2022-01-09_13.06.31-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7835751/crash-2022-01-09_13.06.31-client.txt)
Same crash. I'm seeing a lot of the same mods shared among these logs. Does not happen by itself and Valhelsia core.

**Comment by MercilessArchitect** [comment]
same crash. huh.

**Comment by stal111** [comment]
Could you please check if this issue still occurs with forbidden & arcanus 1.18.1-2.0.1 and newest forge?

**Comment by Klouver-github** [comment]
it does as well, I just ran it, it gave same caused with the skull as well

**Comment by iron-shennon** [comment]
Seems to be working so far on my end with no issues using the latest F&A and the newest Valhelsia core!

**Comment by jkwphysics** [comment]
> Seems to be working so far on my end with no issues using the latest F&A and the newest Valhelsia core!

The problem doesn't seem to go away for me with the latest 2.0.2 and latest Valhelsia Core 0.3.2

```
[18:04:49] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
com.google.gson.JsonParseException: Error loading registry data: Unknown tag: forbidden_arcanus:darkstone_ore_replaceables
	at net.minecraft.core.RegistryAccess.m_175498_(RegistryAccess.java:156) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.core.RegistryAccess.m_175503_(RegistryAccess.java:155) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.core.RegistryAccess.m_175500_(RegistryAccess.java:146) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.resources.RegistryReadOps.m_195841_(RegistryReadOps.java:37) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.core.RegistryAccess.m_123086_(RegistryAccess.java:104) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1905) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.Minecraft.m_91200_(Minecraft.java:1873) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:436) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:342) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_101377_(SelectWorldScreen.java:70) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.MouseHandler.lambda$onPress$0(MouseHandler.java:88) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:101) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer-forge-1.25-mc1.18.jar%23126!/:1.25-mc1.18]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2344!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.handler$zga000$handleWaitEventsTimeout(RenderSystem.java:1968) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1065) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.59.jar%2323!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
[18:05:15] [Render thread/INFO]: Stopping!
[18:05:16] [Render thread/INFO]: Shutting down map thread
```
