### ISSUE TITLE
1.18.1 Crashes when launching the game

### ISSUE THREAD

**Issue by Edison12300** [stal111/Forbidden-Arcanus#229]
Here's the crash report
[crash-2022-01-14_16.56.07-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7869143/crash-2022-01-14_16.56.07-client.txt)

**Comment by Kamil-Suhak** [comment]
Im getting the same crash on forge 39.0.20

**Comment by Kamil-Suhak** [comment]
Temporary fix: downgrading Valhelsia Core to v0.2.1. A clean instance with just F&A and Valhelsia Core works just fine, seems to be a mod compat issue but i cant pinpoint anything

**Comment by Edison12300** [comment]
Yeah, I think it's a mod compat issue. With all my other mods, even dowgrading doesn't work.

**Comment by joedragon** [comment]
Hi, yea I have been having the same problem, the two other mods I have found that cause it to crash are blue_skies-1.18.1-1.3.0 and OSECA-Forge-1.18-4.0.1. removing both of these mods allowed my game to start.

**Comment by Edison12300** [comment]
Just tested every mod out, and turns out it's the wither skeleton tweaks mod causing mine to crash.

**Comment by Edison12300** [comment]
> Hi, yea I have been having the same problem, the two other mods I have found that cause it to crash are blue_skies-1.18.1-1.3.0 and OSECA-Forge-1.18-4.0.1. removing both of these mods allowed my game to start.

I can run with blue skies 1.3.1 no problem

**Comment by Kamil-Suhak** [comment]
Started getting the same crash even with Valhelsia Core v0.2.1 i have no clue whats going on.

**Comment by stal111** [comment]
This issue should be fixed in version 1.18.1-0.2.1. Would be awesome if anyone could test it though to ensure it fixed all conflicts.

**Comment by MarkusBordihn** [comment]
Thanks for the fix, seems to fix the reported issue. But see a incompatibility issue with Create:
```
java.lang.IllegalArgumentException: Failed to create model for minecraft:zombie_villager
	at net.minecraft.client.renderer.entity.EntityRenderers.lambda$createEntityRenderers$2(EntityRenderers.java:55) 
...
Caused by: java.lang.IllegalArgumentException: No model for layer forbidden_arcanus:obsidian_skull#main
	at net.minecraft.client.model.geom.EntityModelSet.m_171103_(EntityModelSet.java:17) ~[client-1.18.1-20211210.034407-srg.jar%23220!:?] {re:classloading,re:mixin}
	at com.stal111.forbidden_arcanus.client.renderer.block.ObsidianSkullRenderer.createModels(ObsidianSkullRenderer.java:48) ~[forbidden_arcanus-1.18.1-2.0.1.jar%23124!:1.18.1-2.0.1] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.entity.layers.CustomHeadLayer.handler$zhm000$forbiddenArcanus_init(CustomHeadLayer.java:540) ~[client-1.18.1-20211210.034407-srg.jar%23220!:?] {re:mixin,re:classloading,pl:mixin:APP:forbidden_arcanus.mixins.json:CustomHeadLayerMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.layers.CustomHeadLayer.<init>(CustomHeadLayer.java:50) ~[client-1.18.1-20211210.034407-srg.jar%23220!:?] {re:mixin,re:classloading,pl:mixin:APP:forbidden_arcanus.mixins.json:CustomHeadLayerMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.HumanoidMobRenderer.<init>(HumanoidMobRenderer.java:20) ~[client-1.18.1-20211210.034407-srg.jar%23220!:?] {re:classloading}
	at net.minecraft.client.renderer.entity.HumanoidMobRenderer.<init>(HumanoidMobRenderer.java:14) ~[client-1.18.1-20211210.034407-srg.jar%23220!:?] {re:classloading}
	at net.minecraft.client.renderer.entity.ZombieVillagerRenderer.<init>(ZombieVillagerRenderer.java:14) ~[client-1.18.1-20211210.034407-srg.jar%23220!:?] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRenderers.lambda$createEntityRenderers$2(EntityRenderers.java:51) ~[client-1.18.1-20211210.034407-srg.jar%23220!:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	... 115 more
```

Create seems only to work with the following versions, but not with newer versions:
<img width="668" alt="create" src="https://user-images.githubusercontent.com/12183293/149664729-17ff2fef-9cbc-469d-88af-dd6ef10ccfe7.png">

**Comment by Kamil-Suhak** [comment]
Please don't post full crash reports, upload the file or a link to a gist/pastebin. 

> This issue should be fixed in version 1.18.1-0.2.1. Would be awesome if anyone could test it though to ensure it fixed all conflicts.

Seems to be fixed for me, thanks

**Comment by Edison12300** [comment]
> This issue should be fixed in version 1.18.1-0.2.1. Would be awesome if anyone could test it though to ensure it fixed all conflicts.

Gonna test it out. Also, I think you mean version 2.0.1, right?

**Comment by joedragon** [comment]
> This issue should be fixed in version 1.18.1-0.2.1. Would be awesome if anyone could test it though to ensure it fixed all conflicts.


Hi, thanks for the quick fix, it all seems to be working for me fine, both mods that were causing me problems now no longer crash the game. Thanks :)

**Comment by dumpsters** [comment]
[crash-2022-01-16_17.33.16-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7877891/crash-2022-01-16_17.33.16-client.txt)
Been crashing since updating to latest Forbidden Arcanus.

**Comment by Edison12300** [comment]
Now I'm getting this crash. It mentioned something about the obsidian skull.
[crash-2022-01-17_21.28.43-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7882157/crash-2022-01-17_21.28.43-client.txt)

**Comment by stal111** [comment]
Closing this as the original issue has been resolved. The issue involving the obsidian skull can be tracked in #219.
