### ISSUE TITLE
Block tag for standing signs are broken

### ISSUE THREAD

**Issue by WenXin20** [stal111/Forbidden-Arcanus#27]
**Describe the bug**
This seems to affect the `standing_signs.json` datapack.
I discovered the text below in the log:

**To Reproduce**
1. Load up a world.
2. Check the log

**Expected behavior**
Tags should function properly

**Version(please complete the following information):**
 - `Forbidden & Arcanus: v1.5-beta3`
 - `Forge: v28.1.106`
- `Minecraft: v1.14.4`
```
[19:11:06] [Server-Worker-15/ERROR]: Couldn't read block tag list minecraft:standing_signs from minecraft:tags/blocks/standing_signs.json in data pack forbidden_arcanus-1.14.4-1.5-beta-3.jar
com.google.gson.JsonParseException: Unknown value 'forbidden_arcanus:mysterywood_sign'
	at net.minecraft.tags.Tag$Builder.lambda$fromJson$0(Tag.java:156) ~[?:?]
	at net.minecraft.tags.Tag$Builder$$Lambda$10983/2140815313.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at net.minecraft.tags.Tag$Builder.func_219783_a(Tag.java:155) ~[?:?]
	at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:101) [?:?]
	at net.minecraft.tags.TagCollection$$Lambda$10971/478651462.get(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
```

**Comment by stal111** [comment]
Should be fixed in 1.14.4-1.5-beta-4
