### ISSUE TITLE
Server crashing for 1.13.2

### ISSUE THREAD

**Issue by BluSodah** [stal111/Forbidden-Arcanus#3]
I had removed all my mods and i still received this crash as well as notice the same line repeated in the cmd server logs "Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found"
I would love to use your mod. Sadly, I don't know much about the java code because of simple lines such as the one above.

`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/13/19 6:34 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: null
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:157) ~[?:?] {pl:eventbus:A,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:891) ~[?:?] {pl:eventbus:A,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:141) ~[?:?] {pl:eventbus:A,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:44) ~[?:?] {pl:eventbus:A,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:116) ~[?:?] {pl:accesstransformer:B,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:549) [?:?] {pl:accesstransformer:B,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3227126480 bytes (3077 MB) / 4990173184 bytes (4759 MB) up to 4990173184 bytes (4759 MB)
	JVM Flags: 2 total; -Xmx5G -Xms5G
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Profiler Position: N/A (disabled)
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by BluSodah** [comment]
Update: The 1.13.2 beta 3 does seem to be working.

**Comment by stal111** [comment]
Is that the full log?
