### ISSUE TITLE
Deorum Armor missing textures

### ISSUE THREAD

**Issue by WenXin20** [stal111/Forbidden-Arcanus#323]
**Describe the bug**
Deorum Armor when equipped are missing textures.

**To Reproduce**
1. Equip armor
2. View in F5 mode

**Expected behavior**
- It should render the correct texture.

**Screenshots**
![image](https://user-images.githubusercontent.com/12000593/217996089-275c63ba-56b0-4bf7-8983-a61768d1662b.png)

**Versions**
 - Forbidden & Arcanus: v2.1.0
 - Valhelsia Core: v0.5.0
 - Forge: v1.19.2-43.2.3

**Additional context**
- In the logs, it shows this: `Failed to load texture: forbidden_arcanus:textures/models/armor/arcane_gold_layer_2.png`
- Log excerpt: <details>
  <summary>Click Here</summary>
  
  ```java
    [09Feb2023 21:07:07.024] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: forbidden_arcanus:textures/models/armor/arcane_gold_layer_2.png
  java.io.FileNotFoundException: forbidden_arcanus:textures/models/armor/arcane_gold_layer_2.png
	  at net.minecraft.server.packs.resources.ResourceProvider.m_215590_(ResourceProvider.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	  at net.minecraft.server.packs.resources.ResourceProvider.m_215593_(ResourceProvider.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.texture.SimpleTexture$TextureImage.m_118155_(SimpleTexture.java:83) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.texture.SimpleTexture.m_6335_(SimpleTexture.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.texture.SimpleTexture.m_6704_(SimpleTexture.java:29) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.texture.TextureManager.m_118515_(TextureManager.java:94) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.texture.TextureManager.m_118495_(TextureManager.java:65) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.texture.TextureManager.m_118506_(TextureManager.java:117) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.RenderStateShard$TextureStateShard.m_110336_(RenderStateShard.java:239) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.RenderStateShard.m_110185_(RenderStateShard.java:36) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23115!/:?]
	  at net.minecraft.client.renderer.RenderType$CompositeRenderType.m_110526_(RenderType.java:437) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.RenderStateShard.m_110185_(RenderStateShard.java:36) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.RenderType.m_110412_(RenderType.java:380) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_109912_(MultiBufferSource.java:96) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_109916_(MultiBufferSource.java:75) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	  at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_109911_(MultiBufferSource.java:72) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at com.obscuria.obscuretooltips.tooltips.TooltipRenderer.renderEntity(TooltipRenderer.java:305) ~[obscure_tooltips-1.0.api9-1.19.jar%23556!/:1.0]
	  at com.obscuria.obscuretooltips.tooltips.TooltipRenderer.drawArmorPreview(TooltipRenderer.java:269) ~[obscure_tooltips-1.0.api9-1.19.jar%23556!/:1.0]
	  at com.obscuria.obscuretooltips.tooltips.TooltipRenderer.drawTooltip(TooltipRenderer.java:80) ~[obscure_tooltips-1.0.api9-1.19.jar%23556!/:1.0]
	  at com.obscuria.obscuretooltips.tooltips.TooltipRenderer.onTooltip(TooltipRenderer.java:51) ~[obscure_tooltips-1.0.api9-1.19.jar%23556!/:1.0]
	  at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2379!/:?]
	  at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2379!/:?]
	  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	  at net.minecraftforge.client.ForgeHooksClient.onRenderTooltipPre(ForgeHooksClient.java:1016) ~[forge-1.19.2-43.2.3-universal.jar%23650!/:?]
	  at net.minecraft.client.gui.screens.Screen.m_169383_(Screen.java:232) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at me.shedaniel.rei.impl.client.gui.forge.ScreenOverlayImplForge.renderTooltipInner(ScreenOverlayImplForge.java:64) ~[RoughlyEnoughItems-9.1.587.jar%23589!/:?]
	  at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltip(ScreenOverlayImpl.java:327) ~[RoughlyEnoughItems-9.1.587.jar%23589!/:?]
	  at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lambda$lateRender$3(ScreenOverlayImpl.java:318) ~[RoughlyEnoughItems-9.1.587.jar%23589!/:?]
	  at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	  at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lateRender(ScreenOverlayImpl.java:318) ~[RoughlyEnoughItems-9.1.587.jar%23589!/:?]
	  at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$24(RoughlyEnoughItemsCoreClient.java:454) ~[RoughlyEnoughItems-9.1.587.jar%23589!/:?]
	  at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	  at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-6.5.69-forge.jar%23406!/:?]
	  at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-6.5.69-forge.jar%23406!/:?]
	  at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%23115!/:?]
	  at jdk.proxy3.$Proxy173.render(Unknown Source) ~[?:?]
	  at dev.architectury.event.forge.EventHandlerImplClient.eventDrawScreenEvent(EventHandlerImplClient.java:147) ~[architectury-6.5.69-forge.jar%23406!/:?]
	  at dev.architectury.event.forge.__EventHandlerImplClient_eventDrawScreenEvent_Post.invoke(.dynamic) ~[architectury-6.5.69-forge.jar%23406!/:?]
	  at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	  at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:441) ~[forge-1.19.2-43.2.3-universal.jar%23650!/:?]
	  at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:433) ~[forge-1.19.2-43.2.3-universal.jar%23650!/:?]
	  at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23645!/:?]
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	  at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	  at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?]
	  at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	  at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	  at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	  at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	  at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	  at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
  ```
  
</details>

**Comment by stal111** [comment]
Fixed in 1.19.2-2.1.1
