### ISSUE TITLE
Incompatibility with Optifine and JEI+EMI: InjectionError: LVT in net/minecraft/client/gui/GuiGraphics... has incompatible changes at opcode 345 in callback forbidden_arcanus.mixins.json

### ISSUE THREAD

**Issue by ChlodAlejandro** [stal111/Forbidden-Arcanus#388]
**Describe the bug**
Installing Optifine, JEI, and EMI alongside Forbidden and Arcanus causes issues when viewing crafting recipes. The crafting recipe converts into an "Error Rendering" panel, and a non-fatal crash report is posted onto a tooltip.

**To Reproduce**
1. Install Optifine, EMI, and Forbidden & Arcanus on Forge 47.2.19 (Minecraft 1.20.1)
2. Open crafting recipe for almost anything
3. Hover over a specific recipe
4. Bug reproduced

**Expected behavior**
The recipe (and tooltips) work as they should.

**Screenshots**
![2024-01-09_06 46 56](https://github.com/stal111/Forbidden-Arcanus/assets/12129227/b6805488-6a29-4304-9227-1e3704281ad5)

**Versions**
 - Forbidden & Arcanus: 2.2.4
 - Valhelsia Core: 1.1.1
 - Forge: 47.2.19
 - Optifine: 1.20.1 HD U I6
 - JEI: 15.2.0.27
 - EMI: 1.0.30

**Additional context**
Relevant exception stacktrace is printed to console, pasted below. See [`latest.log`](https://github.com/stal111/Forbidden-Arcanus/files/13867123/latest.log) for additional data (game was intentionally crashed to get clean system details).
<details>
<summary>Relevant exception</summary>
<pre>
[09Jan2024 06:58:32.063] [Render thread/ERROR] [net.optifine.Log/]: [OptiFine] 
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:744) ~[OptiFine_1.20.1_HD_U_I6.jar%23168!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1402) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/client/gui/GuiGraphics::m_280497_(Lnet/minecraft/client/gui/Font;Ljava/util/List;IILnet/minecraft/client/gui/screens/inventory/tooltip/ClientTooltipPositioner;)V has incompatible changes at opcode 345 in callback forbidden_arcanus.mixins.json:ScreenMixin->@Inject::forbiddenArcanus_renderTooltipInternal(Lnet/minecraft/client/gui/Font;Ljava/util/List;IILnet/minecraft/client/gui/screens/inventory/tooltip/ClientTooltipPositioner;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraftforge/client/event/RenderTooltipEvent$Pre;)V.
 Expected: [Lnet/minecraftforge/client/event/RenderTooltipEvent$Pre;]
    Found: [Ljava/lang/Object;]
Available: [Ljava/lang/Object;, I, I, I, I, Lorg/joml/Vector2ic;, I, I, I, Lnet/minecraft/client/gui/Font;, I, I, Lnet/minecraft/client/gui/screens/inventory/tooltip/ClientTooltipComponent;]
	at net.minecraft.client.gui.GuiGraphics.handler$zzo000$forbiddenArcanus_renderTooltipInternal$missing(GuiGraphics.java) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.gui.GuiGraphics.m_280497_(GuiGraphics.java:837) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.gui.GuiGraphics.m_280666_(GuiGraphics.java:726) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.gui.screens.recipebook.RecipeBookPage.m_280625_(RecipeBookPage.java:129) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.gui.screens.recipebook.RecipeBookComponent.m_280545_(RecipeBookComponent.java:275) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.gui.screens.inventory.CraftingScreen.m_88315_(CraftingScreen.java:67) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.19-universal.jar%23167!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.19-universal.jar%23167!/:?]
	... 31 more
</pre>
</details>
<details>
<summary>System Details</summary>
<pre>
-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.9, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2312704096 bytes (2205 MiB) / 3485466624 bytes (3324 MiB) up to 8518631424 bytes (8124 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce 940MX
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x134d
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2206
	Graphics card #1 name: Intel(R) HD Graphics 620
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x5916
	Graphics card #1 versionInfo: DriverVersion=31.0.101.2111
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 35580.23
	Virtual memory used (MB): 24709.73
	Swap memory total (MB): 2944.00
	Swap memory used (MB): 162.23
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8124m
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Intel(R) HD Graphics 620 GL version 4.6.0 - Build 31.0.101.2111, Intel
	Window size: 1366x745
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 4x Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Chlod'/175, l='ServerLevel[test]', x=12.85, y=86.74, z=-53.99]]
	Data Packs: vanilla, mod:forge, mod:valhelsia_core (incompatible), mod:forbidden_arcanus (incompatible), mod:emi (incompatible), mod:jei
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		emi-1.0.30+1.20.1+forge.jar                       |EMI                           |emi                           |1.0.30+1.20.1+forge |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.19-universal.jar                |Forge                         |forge                         |47.2.19             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		valhelsia_core-forge-1.20.1-1.1.1.jar             |Valhelsia Core                |valhelsia_core                |1.1.1               |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		forbidden_arcanus-1.20.1-2.2.4.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.20.1-2.2.4        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b5ec566b-1b5c-4526-9842-e92ead784d2b
	FML: 47.2
	Forge: net.minecraftforge:47.2.19
</pre>
</details>

**Comment by fronczek7f** [comment]
I also have this problem, I using ATM9 modpack with OptiFine_1.20.1_HD_U_I6 and it looks like optifine is againg a problem. Problem disapear after deleting Optifine or Forbidden Arcanus mod, JEI back to work normally. So if mod autor will not be able to fix this according to know fact that Optifine is closed source mod, than only possible option to fix this by ourselfs by delete Optifine/Forbidden Arcanus. Meh...

**Comment by stal111** [comment]
No intentions to fix incompatibilities caused by Optifine. There are far better alternatives by now you should use instead.
