### ISSUE TITLE
recipe causing emi to break (sync)

### ISSUE THREAD

**Issue by VaporeonScripts** [stal111/Forbidden-Arcanus#443]
**Describe the bug**
the mod breaks emi due to recipes

**To Reproduce**
install emi and latest neoforge 1.21.1 version of F & A

**Expected behavior**
emi to work

**Screenshots**
![image](https://github.com/user-attachments/assets/59498fe8-4456-4a6d-815a-210cd9558665)

**Versions**
 - Forbidden & Arcanus: latest
 - Valhelsia Core: latest
 - NeoForge: 1.21.1 .68

**Additional context**
https://mclo.gs/jO78Wtv

**specific error code:**
Caused by: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:update_recipes'
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:38) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:14) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.filters.GenericPacketSplitter.receivedPacket(GenericPacketSplitter.java:153) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.filters.GenericPacketSplitter.handle(GenericPacketSplitter.java:69) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.handling.MainThreadPayloadHandler.lambda$handle$0(MainThreadPayloadHandler.java:16) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:60) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
	... 29 more
Caused by: io.netty.handler.codec.DecoderException: Failed to decode json: Failed to parse either. First: Failed to parse either. First: Not a json array: {"items":"productivebees:spawn_egg_configurable_bee","components":{"minecraft:entity_data":{"type":"productivebees:gold","id":"productivebees:configurable_bee"}},"type":"productivebees:component"}; Second: Not a json array: "productivebees:spawn_egg_configurable_bee"; Second: No key first in MapLike[{"items":"productivebees:spawn_egg_configurable_bee","components":{"minecraft:entity_data":{"type":"productivebees:gold","id":"productivebees:configurable_bee"}},"type":"productivebees:component"}]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.FriendlyByteBuf.lambda$readJsonWithCodec$2(FriendlyByteBuf.java:105) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:mixin,re:classloading,pl:mixin:APP:packetfixer-common.mixins.json:FriendlyByteBufMixin from mod packetfixer,pl:mixin:A}
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23108!/:?] {re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.FriendlyByteBuf.readJsonWithCodec(FriendlyByteBuf.java:105) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:mixin,re:classloading,pl:mixin:APP:packetfixer-common.mixins.json:FriendlyByteBufMixin from mod packetfixer,pl:mixin:A}
	at TRANSFORMER/forbidden_arcanus@2.5.6-beta/com.stal111.forbidden_arcanus.common.item.crafting.ClibanoRecipe$Serializer.fromNetwork(ClibanoRecipe.java:210) ~[forbidden_arcanus-1.21.1-2.5.6-beta.jar%23763!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$1.decode(StreamCodec.java:20) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$6.decode(StreamCodec.java:108) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$8.decode(StreamCodec.java:150) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.ByteBufCodecs$21.decode(ByteBufCodecs.java:364) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.ByteBufCodecs$21.decode(ByteBufCodecs.java:358) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$7.decode(StreamCodec.java:130) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:91) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:87) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:36) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:14) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.filters.GenericPacketSplitter.receivedPacket(GenericPacketSplitter.java:153) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.filters.GenericPacketSplitter.handle(GenericPacketSplitter.java:69) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.handling.MainThreadPayloadHandler.lambda$handle$0(MainThreadPayloadHandler.java:16) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:60) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?]

**Comment by VaporeonScripts** [comment]
https://github.com/emilyploszaj/emi/issues/748#issuecomment-2407890660

**Comment by VaporeonScripts** [comment]
downgrading to version before latest of arcanus fixed the issue

**Comment by VaporeonScripts** [comment]
somethings wrong with ur latest update

**Comment by VaporeonScripts** [comment]
this issue its for any JEI/EMI/REI mod, its critical

**Comment by SiverDX** [comment]
productive bee's recipe
(https://github.com/JDKDigital/productive-bees/blob/01bac3a8d0f24c783d5ceb052e6f2e380a6cd96e/src/main/resources/data/productivebees/recipe/forbidden_arcanus/clibano_combustion/deorum_bee.json)

might need to be updated to the latest recipe changes for the furnace thingy

**Comment by VaporeonScripts** [comment]
what can i do ?

**Comment by VaporeonScripts** [comment]
its on forbidden and arcanus side, not productive bee's

**Comment by VaporeonScripts** [comment]
https://github.com/JDKDigital/productive-bees/issues/580#issuecomment-2408049991

**Comment by stal111** [comment]
This was fixed in version 1.21.1-2.5.7-beta
