### ISSUE TITLE
1.15.2 - 1.3.1 - crash on startup

### ISSUE THREAD

**Issue by Jorge-M** [stal111/Forbidden-Arcanus#60]
Full startup log below in a version where F&A is the only installed mod, several exceptions.

Using:
MultiMinecraft to maintain minecraft environments
Forge 31.1.0
LWJGL 3 3.2.2

```java
MultiMC version: 0.6.11-1430


Minecraft folder is:
D:/home/Desktop/MultiMC/instances/forbidden arcanus/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/java.exe


Java is version 1.8.0_211, using 64-bit architecture.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  D:/home/Desktop/MultiMC/instances/forbidden arcanus/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  D:/home/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  D:/home/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/home/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/home/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/home/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/home/Desktop/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  D:/home/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  D:/home/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  D:/home/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/home/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/home/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/home/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/home/Desktop/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  D:/home/Desktop/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  D:/home/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/home/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  D:/home/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/home/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/home/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/home/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/home/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  D:/home/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  D:/home/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  D:/home/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  D:/home/Desktop/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.1/ForgeWrapper-1.4.1.jar
  D:/home/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.15.2-31.1.0/forge-1.15.2-31.1.0-launcher.jar
  D:/home/Desktop/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
  D:/home/Desktop/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
  D:/home/Desktop/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
  D:/home/Desktop/MultiMC/libraries/cpw/mods/modlauncher/5.0.0-milestone.4/modlauncher-5.0.0-milestone.4.jar
  D:/home/Desktop/MultiMC/libraries/cpw/mods/grossjava9hacks/1.1.0/grossjava9hacks-1.1.0.jar
  D:/home/Desktop/MultiMC/libraries/net/minecraftforge/accesstransformers/2.0.0-milestone.1-shadowed/accesstransformers-2.0.0-milestone.1-shadowed.jar
  D:/home/Desktop/MultiMC/libraries/net/minecraftforge/eventbus/2.0.0-milestone.1-service/eventbus-2.0.0-milestone.1-service.jar
  D:/home/Desktop/MultiMC/libraries/net/minecraftforge/forgespi/2.0.0-milestone.1/forgespi-2.0.0-milestone.1.jar
  D:/home/Desktop/MultiMC/libraries/net/minecraftforge/coremods/2.0.0-milestone.1/coremods-2.0.0-milestone.1.jar
  D:/home/Desktop/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  D:/home/Desktop/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
  D:/home/Desktop/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
  D:/home/Desktop/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  D:/home/Desktop/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  D:/home/Desktop/MultiMC/libraries/net/jodah/typetools/0.6.1/typetools-0.6.1.jar
  D:/home/Desktop/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  D:/home/Desktop/MultiMC/libraries/com/mojang/minecraft/1.15.2/minecraft-1.15.2-client.jar

Native libraries:
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  D:/home/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  D:/home/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] forbidden_arcanus-1.15.2-1.3.1

Params:
  --username  --version MultiMC5 --gameDir D:/home/Desktop/MultiMC/instances/forbidden arcanus/.minecraft --assetsDir D:/home/Desktop/MultiMC/assets --assetIndex 1.15 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 31.1.0 --fml.mcVersion 1.15.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20200122.131323

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 11720


Using onesix launcher.

2020-04-23 11:25:31,355 main WARN Advanced terminal features are not available in this environment
[32m[11:25:31] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, neo_jman, --version, MultiMC5, --gameDir, D:/home/Desktop/MultiMC/instances/forbidden arcanus/.minecraft, --assetsDir, D:/home/Desktop/MultiMC/assets, --assetIndex, 1.15, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.1.0, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200122.131323, --width, 854, --height, 480]
[m[32m[11:25:31] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.0.0-milestone.4+67+b1a340b starting: java version 1.8.0_211 by Oracle Corporation
[m[32m[11:25:31] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[m[33m[11:25:31] [main/WARN] [ne.mi.fm.lo.FMLConfig/CORE]: Configuration file D:\home\Desktop\MultiMC\instances\forbidden arcanus\.minecraft\config\fml.toml is not correct. Correcting
[m[33m[11:25:31] [main/WARN] [ne.mi.fm.lo.FMLConfig/CORE]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[m[32m[11:25:32] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, MultiMC5, --gameDir, D:\home\Desktop\MultiMC\instances\forbidden arcanus\.minecraft, --assetsDir, D:\home\Desktop\MultiMC\assets, --uuid, <PROFILE ID>, --username, neo_jman, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 854, --height, 480]
[m[32m[11:25:34] [Render thread/INFO] [minecraft/Minecraft]: Setting user: neo_jman
[m[32m[11:25:41] [Render thread/INFO] [minecraft/Minecraft]: Backend library: LWJGL version 3.2.2 build 10
[m[32m[11:25:45] [Render thread/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `edelwood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[m[32m[11:25:45] [Render thread/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `edelwood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[m[32m[11:25:45] [Render thread/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `cherrywood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[m[32m[11:25:45] [Render thread/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `cherrywood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[m[32m[11:25:45] [Render thread/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `mysterywood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[m[32m[11:25:45] [Render thread/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `mysterywood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[m[32m[11:25:45] [modloading-worker-1/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 31.1.0, for MC 1.15.2 with MCP 20200122.131323
[m[32m[11:25:45] [modloading-worker-1/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v31.1.0 Initialized
[m[1;31m[11:25:45] [modloading-worker-3/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: forbidden_arcanus, class com.stal111.forbidden_arcanus.Main
java.lang.NoClassDefFoundError: net/minecraftforge/common/loot/GlobalLootModifierSerializer
	at com.stal111.forbidden_arcanus.Main.<init>(Main.java:89) ~[?:1.15.2-1.3.1] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_211] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_211] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_211] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_211] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:31.1] {re:classloading}
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_211] {}
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_211] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_211] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_211] {}
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_211] {}
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.loot.GlobalLootModifierSerializer
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_211] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211] {}
	... 20 more
[m[1;31m[11:25:45] [Render thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[m[1;31m[11:25:45] [Render thread/FATAL] [ne.mi.ev.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:393) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft-1.15.2-client.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.0-launcher.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39) [ForgeWrapper-1.4.1.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
[m[32m[11:25:46] [Render thread/INFO] [mojang/NarratorWindows]: Narrator library for x64 successfully loaded
[m[32m[11:25:46] [Render thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, Mod Resources
[m[33m[11:25:46] [Server-Worker-4/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Configuration file D:\home\Desktop\MultiMC\instances\forbidden arcanus\.minecraft\config\forge-client.toml is not correct. Correcting
[m[33m[11:25:46] [Server-Worker-4/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key client was corrected from null to SimpleCommentedConfig:{}
[m[33m[11:25:46] [Server-Worker-4/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key client.zoomInMissingModelTextInGui was corrected from null to false
[m[33m[11:25:46] [Server-Worker-4/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key client.forgeCloudsEnabled was corrected from null to true
[m[33m[11:25:46] [Server-Worker-4/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key client.disableStairSlabCulling was corrected from null to false
[m[33m[11:25:46] [Server-Worker-4/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key client.alwaysSetupTerrainOffThread was corrected from null to false
[m[33m[11:25:46] [Server-Worker-4/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key client.forgeLightPipelineEnabled was corrected from null to true
[m[33m[11:25:46] [Server-Worker-4/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key client.selectiveResourceReloadEnabled was corrected from null to true
[m[33m[11:25:46] [Server-Worker-4/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key client.showLoadWarnings was corrected from null to true
[m[1;31m[11:25:46] [Server-Worker-4/ERROR] [ne.mi.fm.ModLoader/LOADING]: Skipping lifecycle event SETUP, 1 errors found.
[m[1;31m[11:25:46] [Server-Worker-4/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[m[1;31m[11:25:46] [Server-Worker-4/FATAL] [ne.mi.ev.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_211] {}
[m[1;31m[11:25:48] [Server-Worker-6/ERROR] [ne.mi.fm.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[m[1;31m[11:25:48] [Server-Worker-6/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[m[1;31m[11:25:48] [Server-Worker-6/FATAL] [ne.mi.ev.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:137) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:107) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture.uniRun(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_211] {}
[m[32m[11:25:48] [Render thread/INFO] [minecraft/SoundSystem]: OpenAL initialized.
[m[32m[11:25:48] [Render thread/INFO] [minecraft/SoundEngine]: Sound engine started
[m[32m[11:25:48] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[m[32m[11:25:48] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[m[32m[11:25:48] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[m[32m[11:25:48] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[m[32m[11:25:48] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[m[32m[11:25:48] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[m[32m[11:25:48] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[m[32m[11:25:49] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[m[32m[11:25:49] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[m[32m[11:25:49] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas

```

**Comment by stal111** [comment]
Try updating your forge version as 31.1.0 is heavily outdated

**Comment by Jorge-M** [comment]
31.1.0 is the currently recommended version on the forge site, http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.15.2.html. "Heavily" is a stretch. 

Updating to the latest forge version fixed the problem.
