### ISSUE TITLE
Vines on Dark Stone

### ISSUE THREAD

**Issue by nckcffmn** [stal111/Forbidden-Arcanus#93]
```
←[m←[33m[13:08:21] [Server thread/WARN] [minecraft/EntityType]: Skipping Entity with id clumps:xp_orb_big
←[m←[1;31m[13:08:47] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}
Caused by: java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=east, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{forbidden_arcanus:arcane_crystal_ore}
        at net.minecraft.state.StateHolder.func_206870_a(SourceFile:114) ~[?:?] {re:classloading,re:mixin}
        at net.minecraft.block.VineBlock.func_196544_a(VineBlock.java:228) ~[?:?] {re:classloading}
        at net.minecraft.block.VineBlock.func_225542_b_(VineBlock.java:212) ~[?:?] {re:classloading}
        at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:617) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs.mixins.json:AbstractBlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:501) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:endergetic:patch_server_world,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(SourceFile:390) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_261] {}
        at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:368) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:337) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:326) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:endergetic:patch_server_world,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        ... 5 more
←[m```

**Comment by Schlock-Konn** [comment]
https://github.com/AllTheMods/ATM-6/issues/42#issuecomment-671012577
